### PR TITLE
Added cellarea and contfrac

### PR DESCRIPTION
**Pull request by jschewe**
Added two variables in water_global.

### CODE REVIEW

**Comment by jochenklar** [comment]
Please add the variables also in this file: https://github.com/ISI-MIP/isimip-protocol-3/blob/master/protocol/04.output/water_global.md at the desired position in the table.

**Comment by jschewe** [comment]
did so, hope it works.

**Comment by jschewe** [comment]
Hi @jochenklar  somehow these two variables don't appear in the "static" variable list, even though I have added in the table...

**Comment by jochenklar** [comment]
Hi @jschewe , somehow your commit did not end up in this pull request. I think you need to change to the `jakob` branch first.

**Comment by jochenklar** [comment]
Oh I see, you committed directly to master, no problem, I will just merge and all will be fine.

**Comment by jschewe** [comment]
cool, thanks!

**Pull request merged**
